### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by donmega** [fabiofalci/sconsify#1]
Hi,

Great app! Would it be possible to compile a windows version? :)

**Comment by fabiofalci** [comment]
Closing as windows never really was a target. (a windows build would be great though)

**Comment by 89z** [comment]
Doesnt seem like it will work without some major pain:

~~~
# pkg-config --cflags  -- libspotify libspotify
pkg-config: exec: "pkg-config": executable file not found in %PATH%
~~~
