### ISSUE TITLE
Command to pause only

### ISSUE THREAD

**Issue by lisuml** [fabiofalci/sconsify#101]
Something like:
```
sconsify -command pause
```

There are situations when you only want to pause (e.g. locking screen). When using `play_pause` command when the current song is paused, when locking it will cause song to play again.

**Comment by fabiofalci** [comment]
I've added to readme how I i3lock to pause.

https://github.com/fabiofalci/sconsify#interprocess-commands

**Comment by lisuml** [comment]
Perfect! Thanks a lot. Would also be nice to have it help message. Currently it only shows:
```
-command string
    	Execute a command in the server: replay, play_pause, next
```

**Comment by fabiofalci** [comment]
No problem.

Yep, just fixed for next release: 
https://github.com/fabiofalci/sconsify/blob/master/sconsify.go#L54

:+1:
