### ISSUE TITLE
Asking for a new token every time

### ISSUE THREAD

**Issue by lezohtml** [fabiofalci/sconsify#112]
Hi there, 

the app asks me for a new token each time I run it. Sometimes, it asks for a token again during playing. Is it a issue or is it from me ? 

tks

**Comment by fabiofalci** [comment]
Hi @lezohtml 

Yes, that's correct.
The token is generated by spotify, and they decided how long it'll be valid for. Not much we can do about it.

**Comment by alalfakawma** [comment]
@fabiofalci Is there anyway to automatically ask for a token and save it? So the user does not have to keep getting a token after every hour. 🤔

**Comment by fabiofalci** [comment]
I think you could, somehow, use a headless browser, already logged in on web spotify, and then get the new token.
