### ISSUE TITLE
I hava ALSA lib Error and Youtube on Firefox issue

### ISSUE THREAD

**Issue by abdyek** [fabiofalci/sconsify#118]
This is alsa lib errors before loading my spotify account library:

> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
> attempt to connect to server failed
> connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
> attempt to connect to server failed
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
> connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
> attempt to connect to server failed

But errors aren't a problem for me because it isn't cause to play music.

I have another problem. Sconsify break my youtube on firefox when sconsify run.

**Comment by fabiofalci** [comment]
It looks like you are using ALSA directly, and ALSA can only handle one application at a time. I heard there is an ALSA module called dmix where you can enable multiple applications but I don't know much about it so I can't advise on that.

I have PulseAudio installed on my machine and that can handle multiple applications at the same time.

**Comment by abdyek** [comment]
Thank you for the information. I won't try to make playable multiple app. I wanted to check it. :+1:
