### ISSUE TITLE
No way to show Albums

### ISSUE THREAD

**Issue by sakuramboo** [fabiofalci/sconsify#12]
Currently, sconsify only lists saved playlists from your account. I follow quite a lot of artists and albums and that's where the bulk of my listening is in. It would be great if I could browse the albums and listen to them without having to make individual playlists for each album.

**Comment by fabiofalci** [comment]
Libspotify supports albums and artists so should be possible to add this.

I'll try to add this to next version. Thanks.

**Comment by fabiofalci** [comment]
0.3.0 lists `albums`, `new releases` and `songs` if `-web-api` is used.
