### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by kandros** [fabiofalci/sconsify#15]
Hi fabio, most of the time i just like to shuffle my whole colleciton, are you planning to add "My collection"? ( i have no idea what is called in the english version i mean the place where songs goes after click the Plus sign)

**Comment by fabiofalci** [comment]
Should be easy to add a Playlist with all your tracks and then you can shuffle there.

Will try to include in the next release.

**Comment by fabiofalci** [comment]
I think I misunderstood your question.
We got a shuffle all your collection (all your playlists) mode. Just type `S`.

Is that your issue?

**Comment by kandros** [comment]
I mean "Your Music" > "Songs" , which is not a standard playlist

2015-09-04 10:37 GMT+02:00 Fabio Falci Rodrigues <notifications@github.com>:

**Comment by fabiofalci** [comment]
I see.
That looks like tracks recently added.

Not sure If libspotify expose this information so we can build this. Will check.

**Comment by fabiofalci** [comment]
You can access `songs`, `new releases`, and `albums` when using `-web-api` on 0.3.0.
