### ISSUE TITLE
Option to select audio quality

### ISSUE THREAD

**Issue by mckennajones** [fabiofalci/sconsify#17]
Does libspotify support this? If it does this feature would be great. In the mobile spotify app you can select normal, high, extreme, etc. 

Also do you know what quality sconsify defaults to?

**Comment by fabiofalci** [comment]
I think we can play with bitrates:

https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#gacd590e095b011af42fb10046117846fe

Don't know the default one though.

**Comment by fabiofalci** [comment]
Commit https://github.com/fabiofalci/sconsify/commit/b79eb1d0274273735ce69ea9c552716bcb08b3bd adds a new flag `-preferred-bitrate`

You can choose `96k`, `160k` or `320k` (default).

Next release will include this.
