### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by chrissexton** [fabiofalci/sconsify#2]
I noticed a few minor issues with the setup instructions.

Firstly, you must `brew tap homebrew/binary` before libspotify will be available. In addition, something linked poorly and I needed to link `libspotify.dylib` to `libspotify` to get the project to run. 

After that, I'm a little unsure what keys go where given the instructions do not match the nomenclature that Spotify uses for their API. An example file where the key files go would probably go a ways here. Does this `spotify_appkey.key` file always need to be in the working directory? Seems odd given there's a global configuration file that could store that information.

Even after all of that, it still panics when I log in. (looking into that still)

**Comment by fabiofalci** [comment]
Yeah you're right, I had to do:

    cd /usr/local/opt/libspotify/lib/
    ln -s libspotify.dylib libspotify

And you don't need to bother with API keys, only if you're going to build yourself. I'll probably take that part of the README then.

**Comment by chrissexton** [comment]
To be clear, I am building it myself because the binary is built looking for `libspotify` in `/usr/local` and I have homebrew's root set to `$HOME/local`.

**Comment by fabiofalci** [comment]
To build create spotify/spotify_key_array.key containing your application key as a go array:

    var key = []byte{
        0x02, 0xA2, ...
        ...
        0xA1}

**Comment by oschrenk** [comment]
Trying to build sconsify on OS X and also running into a few issues (proabably just because I don't know how to build go things in general)

Followed the instructions but then I don't know how to create binary. I tried

```
make                                    Sun May 10 17:35:54 CEST 2015
go get ./...
go install: no install location for directory /Users/oliver/Projects/external/sconsify/sconsify outsi
de GOPATH
go install: no install location for directory /Users/oliver/Projects/external/sconsify/spotify outsid
e GOPATH
go install: no install location for directory /Users/oliver/Projects/external/sconsify/ui outside GOP
ATH
make: *** [build] Error 1
```

`go install` works and I have a binary but if I then try to start the application it fails with 

```
Error: open spotify_appkey.key: no such file or directory
```

**Comment by fabiofalci** [comment]
Hi @oschrenk,

Why are you building instead of using existing osx binary? 

If you still need to build, have you created `spotify/spotify_key_array.key` containing your spotify key?

    var key = []byte{
        0x02, 0xA2, ...
        ...
        0xA1}

If yes, try to build a few time because OSX binary building has a bug, sometimes it doesn't recognize the key.

**Comment by oschrenk** [comment]
I didn't see the link. I went from Installation header straight to OS X part and missed it.
