### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by unk1nd** [fabiofalci/sconsify#22]
Seems that search function is not working.
After i hit / and type the search ( Wu Tang Clan ) it shows *Search on the left and the search under.
After that the client crashes.

Terminal freezes totalt and shows this:

sify/sconsify.go:56 +0x76d
goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
goroutine 7 [select, locked to thread]:
github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc20808c000)
/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:886 +0x346
github.com/op/go-libspotify/spotify.func·001()
/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141
created by github.com/op/go-libspotify/spotify.NewSession
/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819
goroutine 9 [select, 16 minutes]:
github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc20808c000)
/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2ad
created by github.com/op/go-libspotify/spotify.NewSession
/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x8c8
goroutine 18 [syscall, 19 minutes, locked to thread]:
runtime.goexit()
/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
goroutine 10 [chan send, 18 minutes]:
github.com/fabiofalci/sconsify/spotify.func·001()
/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:103 +0x62
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates
/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:104 +0xc1
goroutine 11 [chan receive, 19 minutes]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc20803e0a0)
/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:50 +0x25d
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:124 +0x49
goroutine 13 [select, 1 minutes]:
github.com/nsf/termbox-go.func·001()
/home/fabio/go/src/github.com/nsf/termbox-go/api.go:87 +0x43b
created by github.com/nsf/termbox-go.Init
/home/fabio/go/src/github.com/nsf/termbox-go/api.go:106 +0x96a
goroutine 15 [select, 1 minutes]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/fabio/go/src/github.com/nsf/termbox-go/api.go:321 +0x63f
github.com/jroimartin/gocui.func·002()
/home/fabio/go/src/github.com/jroimartin/gocui/gui.go:209 +0x30
created by github.com/jroimartin/gocui.(*Gui).MainLoop
/home/fabio/go/src/github.com/jroimartin/gocui/gui.go:211 +0xbf

Looks like its trying to refer to your home directory?

**Comment by ialbors** [comment]
Maybe related to the Search part of this PR #20 (second commit)

**Comment by unk1nd** [comment]
how do i build the change in the source?
https://github.com/ialbors/sconsify/commit/12d0ca3cf4000771c9c14a16db44006bc2a64832

**Comment by unk1nd** [comment]
can't seem to build it in my go env...

Mind uploading it build so i can test it?

**Comment by fabiofalci** [comment]
It's interesting that the error shows my go path folder, `/home/fabio/go`.
Maybe it's just a golang thing to carry the source code path & lines to have clearer error.

Anyhow, yeah there is a bug in the search.
If you hit arrows keys after or during typing the search it freezes. The workaround is the @ialbors's commit or use VI navigation after searching, `j` or `k` will move you up or down, after you move once you can start to use the arrows keys again.

**Comment by ialbors** [comment]
@unk1nd 
1nd Here it is:

http://wikisend.com/download/777596/sconsify

**Comment by unk1nd** [comment]
thanks @ialbors , seems to be working as intended now.
Did not try the VI navigation.

Like the project @fabiofalci :+1: Keep up the good work you are doing

**Comment by fabiofalci** [comment]
0.2.1 should fix this issue: https://github.com/fabiofalci/sconsify/releases/tag/v0.2.1
Thanks @ialbors

**Comment by ialbors** [comment]
Thank you!
