### ISSUE TITLE
Login Issue?

### ISSUE THREAD

**Issue by mckennajones** [fabiofalci/sconsify#23]
When logging in I get the following output: 
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

It then freezes for about 30 seconds and I can then login

**Comment by fabiofalci** [comment]
Is this freezing before or after you enter your login details?

If it's after then it could be normal as it takes some time to download all the info about your playlists, specially if you have a lot of playlists.
If it's before then it's not normal.

All these warning about ALSA, I get them too. I remember fixing some of them, basically some audio configuration in your computer, but I just ignore them, apparently there is not effect on sconsify (or maybe there is...)

**Comment by mckennajones** [comment]
Ok nevermind then. It is after I login. 

And the ALSA errors don't seem to affect anything...
