### ISSUE TITLE
Pause hotkey behaviour

### ISSUE THREAD

**Issue by mrbohnke** [fabiofalci/sconsify#24]
With streaming paused, when I press `p` to un-pause, track starts from the beginning.
Is this expected?

**Comment by fabiofalci** [comment]
That's not the expected behavior, however that's what libspotify sdk is doing.
Probably we should change from Pause to Stop and try to figure out another way to Pause, not relying on libspotify sdk.

**Comment by fabiofalci** [comment]
Pause fixed here https://github.com/fabiofalci/sconsify/commit/9cddb496d5bcfa7a0035ba8f3e45b14a66490d84

Not really a libspotify sdk bug but a sconsify bug.
