### ISSUE TITLE
[Request] Improved search

### ISSUE THREAD

**Issue by lukeadams** [fabiofalci/sconsify#28]
1. Ability to [search Spotify using prefixes](https://news.spotify.com/us/2008/01/22/searching-spotify/)
   `artist:'the beatles'`
   `artist:'the beatles' album:'please please me'` (maybe allow Shift+enter for one tag per line so quotes arent needed?)
2. Generic searches (keyword `beatles`, e.g.) should display groupings like Spotify does by artist, album then songs (instead of a list of songs as we have now

**Comment by fabiofalci** [comment]
I remember playing with these prefixes when searching a while ago.
At that time I decided to note include anything related to that because I was out of ideas in how to handle and how to present properly to the user.

But yeah, we can try to include something like you suggested in the next release.
