### ISSUE TITLE
What am i doing wrong here?

### ISSUE THREAD

**Issue by donmega** [fabiofalci/sconsify#3]
Running archlinux:

Sconsify - your awesome Spotify music service in a text-mode interface.
Premium account username: (secret)
Password: *********
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (MIXER,'AC97 2ch->4ch Copy Switch',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib setup.c:548:(add_elem) Cannot obtain info for CTL elem (PCM,'IEC958 Playback PCM Stream',0,0,0): No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
panic: spotify: index does not hold a playlist entry

goroutine 6 [running]:
github.com/op/go-libspotify/spotify.(*PlaylistContainer).Playlist(0xc20802b6e0, 0x21, 0x16)
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1412 +0xd6
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc20802a900, 0x0, 0x0)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:19 +0x153
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc20802a900, 0xc208038070, 0x0, 0x0)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:126 +0x6f
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc20802a900, 0xc208038070, 0x0, 0x0)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:95 +0x12c
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc20800a8a0, 0xd, 0xc20800a928, 0x7, 0x8, 0xc20802a8a0, 0xc20800a810, 0x0, 0x0)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:44 +0x26e
github.com/fabiofalci/sconsify/spotify.Initialise(0xc20800a8a0, 0xd, 0xc20800a928, 0x7, 0x8, 0xc20802a8a0, 0xc20800a810)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:24 +0x81
created by main.main
        /home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:55 +0x76d

goroutine 1 [select]:
github.com/fabiofalci/sconsify/sconsify.StartMainLoop(0xc20802a8a0, 0x7f0d912f8d18, 0x93aa58, 0x0, 0x0, 0x0)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/mainloop.go:4 +0x63a
main.main()
        /home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:59 +0x7c1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select, locked to thread]:
github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc208064000)
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:886 +0x346
github.com/op/go-libspotify/spotify.func·001()
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141
created by github.com/op/go-libspotify/spotify.NewSession
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819

goroutine 9 [select]:
github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc208064000)
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2ad
created by github.com/op/go-libspotify/spotify.NewSession
        /home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x8c8

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [sleep]:
github.com/fabiofalci/sconsify/spotify.func·001()
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:101 +0x36
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:103 +0xc1

goroutine 11 [chan receive]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc208038070)
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:50 +0x25d
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
        /home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:123 +0x49

**Comment by fabiofalci** [comment]
Do you have any playlist in your spotify account?
It looks like the code isn't prepared to an account with no playlists.

**Comment by donmega** [comment]
Thx for the fast reply! I have playlists on my Spotify Account. I can temporarliy change my password so you can check it out if you want to. I'll drop you an mail.

**Comment by hirschnase** [comment]
I have the excatly same issue... i get the "panic: spotify: index does not hold a playlist entry" message directly after signing in. And yes, i have a couple of playlists in spotify. Let me know if i can help debug/test.

**Comment by donmega** [comment]
Hi! I've fixed my problem! Make sure to empty your empty playlists :)

**Comment by fabiofalci** [comment]
Libspotify defines a couple of playlist type: https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#gafdd7117213605e6f2671c4f289b44609

And the go wrapper we've been using throws a panic when playlist is different than the default one `SP_PLAYLIST_TYPE_PLAYLIST`.
I'll raise this issue with them to get resolve.

While that doesn't happen you'll need to discover which playlist of yours isn't a normal one. In case of @donmega it was an empty one.

If you don't find and you're up to debug you can print the playlist name here:
https://github.com/fabiofalci/sconsify/blob/master/spotify/spotify_playlists.go#L21

    println(playlist.Name())

And then build and run.

**Comment by fabiofalci** [comment]
Please check #5 for more information.
