### ISSUE TITLE
No results on search

### ISSUE THREAD

**Issue by MikeyR16** [fabiofalci/sconsify#31]
Using ubuntu 14.04
When I'm searching with "/" it doesn't show any results, I can see my playlists and all songs in it but I can't search for e.g. volbeat and get all songs available from volbeat.

Using the latest version of sconsify and I had it to work earlier.

**Comment by fabiofalci** [comment]
Yes, I'm seeing that here as well.

It looks like a spotify issue, the search is not returning anything most of the times.
If you delete the search and try again sometimes you eventually get the results.

**Comment by fabiofalci** [comment]
Today I didn't get one search working. 
Looks like a bad day for libspotify sdk search.

**Comment by MikeyR16** [comment]
Yea I guess it is, well it's just a question about time before it's up again, so I will close the issue

**Comment by fabiofalci** [comment]
Next release will have integration with spotify web api https://developer.spotify.com/web-api/endpoint-reference/

Maybe it's a good idea to move the search to use webapi instead of libspotify sdk as they don't maintain libspotify sdk anymore.
