### ISSUE TITLE
Runs but no sound - Elementary OS Freya

### ISSUE THREAD

**Issue by cowboycodur** [fabiofalci/sconsify#4]
~$ ./sconsify 
Sconsify - your awesome Spotify music service in a text-mode interface.
Premium account username: ***********
Password: ********
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
~$

**Comment by cowboycodur** [comment]
UPDATE: Plays out of analog speakers, but not out of bluetooth speakers.

**Comment by donmega** [comment]
I am no Linux guru, but did you already try to change the default device in ALSA?

**Comment by fabiofalci** [comment]
Maybe an issue between PortAudio and bluetooth speakers?

**Comment by fabiofalci** [comment]
Closing please reopen if still happening.
