### ISSUE TITLE
Can't get it to run - I get these errors after entering username and password.

### ISSUE THREAD

**Issue by oujii** [fabiofalci/sconsify#43]
2016-07-19 18:00:50.374 sconsify[7685:126124] 18:00:50.373 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
panic: spotify: track artist index out of range

goroutine 6 [running]:
github.com/op/go-libspotify/spotify.(*Track).Artist(0xc82056c060, 0x0, 0x4005fac)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1901 +0xd3
github.com/fabiofalci/sconsify/sconsify.ToSconsifyTrack(0xc82056c060, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/track.go:32 +0x39
github.com/fabiofalci/sconsify/spotify.(*Spotify).initTrack(0xc820039e78, 0xc8202c0ac0, 0xc8202c0ac0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:63 +0x97
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc820039e78, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:42 +0x352
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc820039e78, 0xc820028090, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:127 +0x75
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc820039e78, 0xc820028090, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:96 +0x117
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc82000ad90, 0x4, 0xc82000ae50, 0x9, 0x10, 0xc8200169c0, 0xc82000ac50, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:45 +0x241
github.com/fabiofalci/sconsify/spotify.Initialise(0xc82000ad90, 0x4, 0xc82000ae50, 0x9, 0x10, 0xc8200169c0, 0xc82000ac50)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:25 +0x7e
created by main.main
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:56 +0xb12

goroutine 1 [select]:
github.com/fabiofalci/sconsify/sconsify.StartMainLoop(0xc8200169c0, 0x4da4600, 0x4398480, 0x4da4600, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/mainloop.go:4 +0x6ee
main.main()
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:60 +0xd4a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select, locked to thread]:
github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc8200a6580)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:886 +0x372
github.com/op/go-libspotify/spotify.NewSession.func1(0xc8200a6580, 0xc820017e00)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x1a0
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x6e3

goroutine 18 [select]:
github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc8200a6580)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2c1
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x788

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 35 [chan send]:
github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates.func1(0xc820108180)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:103 +0x4f
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:104 +0x5f

goroutine 9 [chan receive]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc820028090)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:50 +0x252
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:124 +0x4a

**Comment by fabiofalci** [comment]
Are you using the latest rc version? https://github.com/fabiofalci/sconsify/releases/tag/v0.3.0-rc1

If not please can you test on that rc version.

Persisting the error run with debug flag `sconsify -debug` which will output loaded tracks to `~/.sconsify/sconsify.log` and then we can find out which track/artist is not loading correctly.

**Comment by mrbohnke** [comment]
I use to get similar (the same?) errors. Right now, this is the discordant track (which, you will find, also fails on desktop client):
`spotify:track:11QKtCdZqoExeoYymlI1VL`

**Comment by fabiofalci** [comment]
Interesting if you try to get this track using web api, it returns a 404, no track.

https://developer.spotify.com/web-api/get-track/

Maybe spotify deletes tracks making them unavailable to load next time? And then sconsify needs to handle that, probably ignoring it.

**Comment by fabiofalci** [comment]
Closing, please reopen if still happening.
