### ISSUE TITLE
How to Build in Raspberry Pi / armv

### ISSUE THREAD

**Issue by jackdesert** [fabiofalci/sconsify#45]
On my raspberry pi3 running jessie I managed to install the dependencies, build glider from source, and install Golang 1.5, but running `make build` is failing to find the libraries that I apt-get installed:

    $ curl http://apt.mopidy.com/mopidy.gpg | sudo apt-key add - && sudo curl -o /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list

    $ sudo apt-get update && sudo apt-get install -y libportaudio2 libspotify12 --no-install-recommends 

    $ make build
    glide -q install
    sed -i '$ d' spotify/key.go && cat spotify/spotify_key_array.key >> spotify/key.go \
        && GO15VENDOREXPERIMENT=1 go build -ldflags "\
         -X main.version=0.3.0-rc1 \
         -X main.commit=d69b4e5 \
         -X main.buildDate=1470001367 \
         -X main.spotifyClientId=4e1fa8c468ce42c2a45c7c9e40e6d9d0 \
         -X main.authRedirectUrl=https://fabiofalci.github.io/sconsify/auth/" \
         -o bundles/sconsify \
        ; git checkout spotify/key.go
    # pkg-config --cflags libspotify libspotify
    Package libspotify was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libspotify.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libspotify' found
    Package libspotify was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libspotify.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libspotify' found
    pkg-config: exit status 1
    # pkg-config --cflags portaudio-2.0
    Package portaudio-2.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `portaudio-2.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'portaudio-2.0' found
    pkg-config: exit status 1

**Comment by fabiofalci** [comment]
The last time I tried to build on rpi 2 was on an archlinux and unfortunately it didn't work very well.
I don't remember why, long time ago.

I can try again to check if was the same error as you had.

**Comment by freistil90** [comment]
I remember getting it working a couple of months back, but I had to recompile a lot. I'll take a look if I still find it.

**Comment by fabiofalci** [comment]
Closing as raspberry pi was never really the main target (a rpi build/instructions would be great though).

**Comment by jhaggqvist** [comment]
If anyone found a solution to this, please post it!

**Comment by fabiofalci** [comment]
It should be no different than MacOS or Linux x86_64 builds. I tried some time ago and worked. However, there are two problems now: libspotify is not available for download and Spotify is not issuing application keys anymore.
