### ISSUE TITLE
UI: Track Display

### ISSUE THREAD

**Issue by brownzach125** [fabiofalci/sconsify#62]
Why did you decide to display songs 
\<author\> - \<title\>?
In spotify it does title then author
I think that makes more sense and is the norm.
Also why include the index? ( \<index\>. \<author\> - \<title\> )
Are you planning on a feature using the index? Otherwise it just kind of clutters up the view. 
What do you think?

P.S I'm not assuming you don't have your reasons. I was just curious.

**Comment by fabiofalci** [comment]
Good question. Maybe we could title then authors. I don't have anything against.
About the index, it helps when using `gg` to jump to a track. However, we could make this configurable. Maybe a configuration to define the title format? Such as:

```
--song-format={title}-{author}
--song-format={index}. {author}-{title}
--song-format={index}. {author}-{title} {duration}

```

**Comment by brownzach125** [comment]
I did not know about the `gg` feature the index makes total sense then. 
Yeah I'd really prefer the default to be `{index}. {title}-{author}` That just seems more user friendly.
But configuration would be the best solution.

**Comment by fabiofalci** [comment]
Ok, cool.
Let's change to `{index}. {title} - {author}` as default and the configuration can be done in another step.

**Comment by fabiofalci** [comment]
Fixed https://github.com/fabiofalci/sconsify/commit/690418629132d8b34ca19c0a5f7935f1e974c222
