### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by chrislovessushi** [fabiofalci/sconsify#67]
panic: runtime error: index out of range

goroutine 19 [running]:
panic(0x805360, 0xc420012100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/webapi.Auth(0x8b5720, 0x20, 0x8b58a0, 0x2b, 0x180001, 0x0)
	/go/src/github.com/fabiofalci/sconsify/webapi/web_auth.go:44 +0x8ac
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc420172000, 0xc420130190, 0xc420146018, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:146 +0x12d
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc420172000, 0xc420130190, 0xc420146018, 0xc4201363d0, 0xc)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:120 +0x5a
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc420130190, 0xc4201342aa, 0x9, 0xc4201363d0, 0xc, 0x10, 0xc42014e080, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:60 +0x22a
github.com/fabiofalci/sconsify/spotify.Initialise(0xc420130190, 0xc4201342aa, 0x9, 0xc4201363d0, 0xc, 0x10, 0xc42014e080)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:39 +0x7a
created by main.main
	/go/src/github.com/fabiofalci/sconsify/sconsify.go:85 +0xaad

**Comment by chrislovessushi** [comment]
That's the output using -web-api, here's the output of just ./sconsify after logging in. Ubuntu 17 btw.

ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Warning: not using -web-api flag. Sconsify will load playlists using deprecated libspotify API. If not working try -web-api flag.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5ebc9a]

goroutine 38 [running]:
panic(0x805360, 0xc42000c0d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio.hostsAndDevices(0x1, 0x1, 0x0, 0xc420023e28, 0x1300419778, 0x7f8d3e820680, 0x0, 0x1000000000002)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio/portaudio.go:323 +0x12a
github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio.Devices(0x7f8d3e820680, 0x45a030, 0x2, 0x8b0f32, 0x8b0ffe)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio/portaudio.go:256 +0x26
github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio.DefaultOutputDevice(0xc420023ef0, 0x419c8e, 0xc42000c310)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio/portaudio.go:280 +0x26
github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio.OpenDefaultStream(0x0, 0x2, 0x40e5888000000000, 0x1000, 0xc42000c310, 0x1, 0x1, 0x0, 0x0, 0xc420174120)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/gordonklaus/portaudio/portaudio.go:647 +0x17e
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc42002a010)
	/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:31 +0x116
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:159 +0x6a

**Comment by fabiofalci** [comment]
Hi,
I can see some odd errors in there. Such as: `Cannot lock down 82274202 byte memory area (Cannot allocate memory)`
Will need a bit of investigation.

However, I can see this as well:

```
Warning: not using -web-api flag. Sconsify will load playlists using deprecated libspotify API. If not working try -web-api flag.
```

This message should not be shown if passing `-web-api`

**Comment by chrislovessushi** [comment]
This is with -web-api:

`panic: runtime error: index out of range

goroutine 19 [running]:
panic(0x805360, 0xc420012100)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/webapi.Auth(0x8b5720, 0x20, 0x8b58a0, 0x2b, 0x180001, 0x0)
/go/src/github.com/fabiofalci/sconsify/webapi/web_auth.go:44 +0x8ac
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc420172000, 0xc420130190, 0xc420146018, 0x0, 0x0)
/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:146 +0x12d
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc420172000, 0xc420130190, 0xc420146018, 0xc4201363d0, 0xc)
/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:120 +0x5a
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc420130190, 0xc4201342aa, 0x9, 0xc4201363d0, 0xc, 0x10, 0xc42014e080, 0x0, 0x0)
/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:60 +0x22a
github.com/fabiofalci/sconsify/spotify.Initialise(0xc420130190, 0xc4201342aa, 0x9, 0xc4201363d0, 0xc, 0x10, 0xc42014e080)
/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:39 +0x7a
created by main.main
/go/src/github.com/fabiofalci/sconsify/sconsify.go:85 +0xaad`

**Comment by fabiofalci** [comment]
Hmm, it seems is failing when reading the token you just copied from the web page.

Does the generate token look like this?

```
access_token:BIG_TOKEN_STRING token_type:Bearer expiresIn:3600
```

It needs to include all that, including the spaces between `access_token`, `token_type`, `expiresIn`.

**Comment by chrislovessushi** [comment]
Okay Im dumb :) I wasn't copying the entire thing, just the access_token. It works beautifully, THANK YOU!
