### ISSUE TITLE
Playing local files doesn't work

### ISSUE THREAD

**Issue by oschrenk** [fabiofalci/sconsify#7]
This might be by design (or because of libspotify) but I have some local files (from old itunes import) mixed with other spotify tracks. There is no feedback that these file can't be played.

**Comment by oschrenk** [comment]
Or offline files for that matter.

**Comment by fabiofalci** [comment]
Yeah, I never tried to play offline tracks. Most probably they're not working.

We should probably check this out in next versions.

**Comment by fabiofalci** [comment]
Closing as there is no plan for this.
