### ISSUE TITLE
Sconsify cant allocate memory?

### ISSUE THREAD

**Issue by Toxcique** [fabiofalci/sconsify#70]
Hi! I have go 1.5 installed and im running sconsify version 0.3.0, installed from the AUR.

When start sconsify with:
`$ sconsify`

i get the output:

`ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot lock down 82274202 byte memory area (Cannot allocate memory)`
`

Can someone help me with this problem? Thanks

**Comment by fabiofalci** [comment]
Hi.
It doesn't need to have golang installed to run sconsify.

That version, 0.3.0, isn't working as libspotify isn't loading playlists anymore.

You should try 0.4.0-rc3.

https://github.com/fabiofalci/sconsify/releases/tag/v0.4.0-rc3

**Comment by Toxcique** [comment]
thanks for the quick reply! It works perfectly now :D
