### ISSUE TITLE
When passing the -web-api flag, sconsify says it's not using the flag and suggests to use it.

### ISSUE THREAD

**Issue by crscillitoe** [fabiofalci/sconsify#71]
Screenshot of issue : https://i.imgur.com/UBOfguV.jpg/

**Comment by fabiofalci** [comment]
That's odd. Can you please test with `-web-api=true`?

We'll change the default value to true next release so it won't be necessary to pass it.

**Comment by fabiofalci** [comment]
Please test with 0.4.0 where the default is true and there's no need to pass the flag. Closing.
