### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by cpny** [fabiofalci/sconsify#8]
Heya, could you tell me what do i need to build from source? I tried exporting the go path etc but even though it compiles fine then it core dumps in the end so guess i did something wrong.

Thanks

Also with the downloaded executable i get this errors:

ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

I have jack and jack32 and libalsa and libalsa32 installed etc.

Cheers, due to this it takes like 1 minute to connect to spotify for some reason.

**Comment by fabiofalci** [comment]
These are warnings about your sound configuration, I get these too.
I've eliminated some of them by doing some extra configuration in alsa/portaudio but I don't remember exactly now.
Anyhow this doesn't affect the app in any obvious way, maybe I'm missing something here but I've been using with these warning with no apparent issues.

Yeah, sometimes it takes more time than usual to log in, not sure yet why but I'd say is network related or spotify is a bit overload in that moment. When that happens I just CTRL-C and try again in 10 or 20 seconds.

To build yourself just need to type:

    make build

And then the binary will be placed in `bundles/sconsify`.

You'll need to have your spotify key defined in `spotify/spotify_key_array.key` too.  And that's pretty much it.

If you happen to be on linux you can use docker to build:

    make binary

Again binary will be place in the same place.

For OSX you can't using docker, you have to use `make build`.
There is an annoying bug for OSX where the build can't get the spotify key sometimes so if after building you get a message about a missing key, just try to build again.

**Comment by cpny** [comment]
Thanks for the reply, i'm using Linux.

Tried doing a make build with go path set as /home/hugo/go and /home/hugo/go/sconsify and getting similar errors for both things.

go install: no install location for directory /home/hugo/go/sconsify outside GOPATH
go install: no install location for directory /home/hugo/go/sconsify/sconsify outside GOPATH
go install: no install location for directory /home/hugo/go/sconsify/spotify outside GOPATH
go install: no install location for directory /home/hugo/go/sconsify/ui outside GOPATH

Any idea what it might be?

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hugo/go/sconsify"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Output for go env.

Thanks once again.

**Comment by fabiofalci** [comment]
As far as I know you set your `GOPATH` and inside you need to have another structure of `bin/pkg/src` folders.

I think the best way is getting the project using `go get`

    go get github.com/fabiofalci/sconsify

This will download in the right structure inside `GOPATH`.

**Comment by cpny** [comment]
Tyvm :), that seems to do the trick.

**Comment by freistil90** [comment]
Might be too late but for future readers:
Set these paths in your bashrc:

export $GOPATH=/your/path/here

Then everything works fine.
