### ISSUE TITLE
Login with facebook created spotify account

### ISSUE THREAD

**Issue by Rimann91** [fabiofalci/sconsify#88]
Apparently, I created my Spotify **with** my Facebook credentials. Is there a way to log in to Sconsify without Spotify specific credentials?  Can I use my facebook creds to log in to Sconsify? If not the only other alternative is very unfortunate. [Looks like creating a whole new premium Spotify account with a different email](https://support.spotify.com/us/account_payment_help/account_help/i-want-to-use-spotify-without-facebook/)

**Comment by c-Brooks** [comment]
Just went through this, Spotify has a solution to this with the Set Device Password feature.

https://www.spotify.com/account/set-device-password/
