### ISSUE TITLE
Error: No playlist to load

### ISSUE THREAD

**Issue by HendrikPetertje** [fabiofalci/sconsify#94]
When starting Sconsify on OSX High sierra in Iterm2 (running TMUX) with the libraries in all the right places I see the following after logging in:

```
▶ ./sconsify
Sconsify - your awesome Spotify music service in a text-mode interface.
Premium account username: MYDEVICELOGIN
Password: *******************
Loaded 50 from 405 playlists
Loaded 100 from 405 playlists
Loaded 150 from 405 playlists
Loaded 200 from 405 playlists
Loaded 250 from 405 playlists
Loaded 300 from 405 playlists
Loaded 350 from 405 playlists
Loaded 0 from 0 playlists
Error: No playlist to load
```

Any idea what's going on here?

**Comment by HendrikPetertje** [comment]
is there some way to run with more verbose output?

**Comment by HendrikPetertje** [comment]
after reopening the app a few times it worked out
must have been a minor connection issue

**Comment by fabiofalci** [comment]
Hi, ok, cool.

Yeah, there is a `-debug` flag that prints some things in the file `~/.sconsify/sconsify.log.`

Also, 405 playlists! I don't have that many playlists, I got only 68, so maybe it just can't handle that number of playlists that well?
